### ISSUE TITLE
Idea: Add permalinks

### ISSUE THREAD

**Issue by RobJN** [osm-uk/envelopes-map#6]
>Please could I request that the page also includes a permalink, such that I don't need to start each session by zooming in? It'd also be useful if I need to share a link in a discussion; I could say "Take a look at the address over here: [Link]".

https://lists.openstreetmap.org/pipermail/talk-gb/2022-January/028458.html

**Comment by rjw62** [comment]
If you'd like to add an automatic dynamically generated/updated hash to the URL in the browser (like the mail OSM site does) the leaflet plugin I use for this on my tools (e.g. https://osm.mathmos.net/survey/ ) is https://github.com/mlevans/leaflet-hash .

**Comment by RobJN** [comment]
Thanks. That was the one I found on a quick google too but is great to hear that it is the same one others use. All integrated now.
